// Drives the real menu flow in Chromium and screenshots each screen.
import { chromium } from 'playwright-core';
import { spawn } from 'node:child_process';
const PORT = 4190;
const server = spawn(process.execPath, ['node_modules/vite/bin/vite.js', '--port', String(PORT), '--strictPort'], { stdio: ['ignore', 'pipe', 'pipe'] });
await new Promise((res) => { server.stdout.on('data', (d) => { if (String(d).includes('localhost')) res(); }); setTimeout(res, 8000); });
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
const errs = [];
page.on('pageerror', (e) => errs.push(e.message));
page.on('console', (m) => { if (m.type() === 'error') errs.push(m.text()); });
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const shot = async (n) => { await page.screenshot({ path: `screenshots/flow-${n}.png` }); console.log('shot', n, await page.evaluate(() => window.__ck.state())); };
const click = (t) => page.evaluate((t) => window.__ck.click(t), t);
await page.goto(`http://localhost:${PORT}/?quality=low`);
await page.evaluate(() => localStorage.clear());
await page.reload();
await sleep(6000);
await click('Play'); await sleep(5000); await shot('select');
await page.locator('.chick-card').nth(1).click(); await sleep(1500);
await click('Confirm'); await sleep(5000); await shot('map');
await click('Play'); await sleep(4000); await shot('intro');
await click('Start!'); await sleep(5000); await shot('play-countdown');
await page.evaluate(() => window.__ck.fastForward(4)); await sleep(4000); await shot('play');
await page.keyboard.press('Escape'); await sleep(2500); await shot('pause');
await click('Resume'); await sleep(500);
await page.evaluate(() => { window.__ck.flow.session.autopilot = new (window.__ck.flow.session.autopilot?.constructor ?? Object)(); });
console.log('errors:', errs.slice(0, 10));
await browser.close(); server.kill();
